 export const stack = [
  { title: "HTML", color: "#E34F26" },        
  { title: "CSS", color: "#1572B6" },         
  { title: "JavaScript", color: "#fc8403" },  
  { title: "React", color: "#61DAFB" },       
  { title: "Next.js", color: "#000000" },     
  { title: "TypeScript", color: "#3178C6" },  
  { title: "MongoDB", color: "#47A248" },     
  { title: "SQL", color: "#F29111" },        
  { title: "Docker", color: "#2496ED" },      
  { title: "Kubernetes", color: "#326CE5" },  
  { title: "Monorepo", color: "#6C757D" },    
  { title: "Turborepo", color: "#000000" },  
  { title: "Framer Motion", color: "#0055FF" },
  { title: "Redis", color: "#DC382D" },       
  { title: "Web Sockets", color: "#00A67E" }, 
  { title: "AWS", color: "#1d2036" },         
];
